image: maven:3.8.4-jdk-11  # Use a Docker image with Maven and JDK

stages:
  - test

selenium_tests:
  stage: test
  before_script:
    - apt-get update -y && apt-get install -y firefox-esr openjdk-11-jdk  # Install necessary packages (adjust for your setup)
    - export DISPLAY=:99  # Setup a virtual display (useful for headless browsers)
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &  # Start Xvfb
    - sleep 3  # Wait for Xvfb to start
  script:
    - mvn clean test  # Command to run Maven tests (adjust as per your Maven project setup)
  artifacts:
    paths:
      - target/cucumber/report/  # Path to save Selenium test reports
  tags:
    - docker  # Example tag for CI environment
