name: Trigger Test Automation

on:
  push:
    branches:
      - development   # Run on pushes to the development branch of software-repo

jobs:
  trigger-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2   # Action to checkout the software-repo's code

      - name: Trigger Test Automation
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.AUTOMATION_1SECRET }}  # Personal Access Token (PAT) with repo scope
          repository: automation-repo
          event-type: run-tests
          ref: main
