name: Trigger Test Automation

on:
  push:
    branches:
      - main   # Run on pushes to the development branch of software-repo

jobs:
  trigger-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2   # Action to checkout the software-repo's code

      - name: Trigger Test Automation
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}  # Personal Access Token (PAT) with repo scope
          repository: ShashankWosler/Telelink_first
          event-type: run-tests
          client-payload: '{}'
