name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust as needed, e.g., '11' for JDK 11

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Send Email Notification
      env:
        SMTP_SERVER: smtp.wosler.ca  # Replace with your SMTP server address
        SMTP_PORT: 587  # Replace with your SMTP port number
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}  # Replace with your SMTP username (stored in GitHub Secrets)
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}  # Replace with your SMTP password (stored in GitHub Secrets)
        FROM_EMAIL: shashank.tiwari@wosler.ca  # Replace with your sender email address
        TO_EMAIL: shashank.tiwari@wosler.ca  # Replace with your recipient email address
        SUBJECT: "GitHub Action Notification"
        BODY: |
          Hello,

          This is a notification email sent from GitHub Actions.

          Regards,
          Your Name

      run: |
        echo "Subject: $SUBJECT" > report.html
        echo "$BODY" >> report.html
        echo "" >> report.html
        echo "Sent from GitHub Actions" >> report.html
        
        sendmail -t < report.html
