name: Send Report Email

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smtplib email

      - name: Create Report
        run: echo "This is the report content." > report.txt  # Replace with your report generation command

      - name: Send Email
        env:
          SMTP_SERVER: smtp.wosler.ca  # Replace with your SMTP server address
          SMTP_PORT: 587  # Replace with your SMTP port number
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}  # Replace with your SMTP username (stored in GitHub Secrets)
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}  # Replace with your SMTP password (stored in GitHub Secrets)
          FROM_EMAIL: shashank.tiwari@wosler.ca  # Replace with your sender email address
          TO_EMAIL: shashank.tiwari@wosler.ca  # Replace with your recipient email address
          SUBJECT: "Report Email"
        run: |
          # Create the email content
          echo -e "Subject: $SUBJECT\nFrom: $FROM_EMAIL\nTo: $TO_EMAIL\nContent-Type: multipart/mixed; boundary=\"BOUNDARY\"\n\n--BOUNDARY\nContent-Type: text/plain; charset=UTF-8\n\nHello,\n\nThis is a report email sent from GitHub Actions.\n\nRegards,\nYour Name\n\n--BOUNDARY\nContent-Type: text/plain; charset=UTF-8\nContent-Disposition: attachment; filename=\"report.txt\"\n\n$(cat report.txt)\n--BOUNDARY--" > email.txt

          # Send the email using curl
          curl --url "smtp://$SMTP_SERVER:$SMTP_PORT" \
               --ssl-reqd \
               --mail-from "$FROM_EMAIL" \
               --mail-rcpt "$TO_EMAIL" \
               --user "$SMTP_USERNAME:$SMTP_PASSWORD" \
               --upload-file email.txt
