name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Send Email with Attachment
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        echo '<html><body><h1>Hello, Shreyas!</h1><p>This is your HTML report.</p></body></html>' > report.html
        base64 report.html > report.html.base64
        curl --request POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer $SENDGRID_API_KEY" \
          --header 'Content-Type: application/json' \
          --data '{
            "personalizations": [
              {
                "to": [
                  {
                    "email": "shashank.tiwari@wosler.ca"
                  }
                ],
                "subject": "Telelink HTML Report"
              }
            ],
            "from": {
              "email": "shashank.tiwari@wosler.ca"
            },
            "content": [
              {
                "type": "text/html",
                "value": "<html><body><h1>Hello, Shreyas!</h1><p>This is your HTML report.</p></body></html>"
              }
            ],
            "attachments": [
              {
                "content": "$(cat report.html.base64)",
                "filename": "report.html",
                "type": "text/html",
                "disposition": "attachment"
              }
            ]
          }'
