name: Send Report Email

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Create Report
        run: echo "This is the report content." > report.txt  # Replace with your report generation command

      - name: Send Email
        env:
          SMTP_SERVER: smtp.wosler.ca  # Replace with your SMTP server address
          SMTP_PORT: 587  # Replace with your SMTP port number
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}  # Replace with your SMTP username (stored in GitHub Secrets)
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}  # Replace with your SMTP password (stored in GitHub Secrets)
          FROM_EMAIL: shashank.tiwari@wosler.ca  # Replace with your sender email address
          TO_EMAIL: shashank.tiwari@wosler.ca  # Replace with your recipient email address
          SUBJECT: "Report Email"
        run: |
          python - <<EOF
          import smtplib
          from email.mime.multipart import MIMEMultipart
          from email.mime.text import MIMEText
          from email.mime.base import MIMEBase
          from email import encoders

          # Email content and attachment
          from_email = "${FROM_EMAIL}"
          to_email = "${TO_EMAIL}"
          subject = "${SUBJECT}"
          body = """\
          Hello,

          This is a report email sent from GitHub Actions.

          Regards,
          Your Name
          """

          attachment_path = "report.txt"

          # Create message container
          message = MIMEMultipart()
          message['From'] = from_email
          message['To'] = to_email
          message['Subject'] = subject

          # Attach body
          message.attach(MIMEText(body, 'plain'))

          # Attach file
          with open(attachment_path, "rb") as attachment:
              part = MIMEBase("application", "octet-stream")
              part.set_payload(attachment.read())
              encoders.encode_base64(part)
              part.add_header(
                  "Content-Disposition",
                  f"attachment; filename= {attachment_path}",
              )
              message.attach(part)

          # Connect to SMTP server and send email
          server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
          server.starttls()
          server.login("${SMTP_USERNAME}", "${SMTP_PASSWORD}")
          text = message.as_string()
          server.sendmail(from_email, to_email, text)
          server.quit()
          EOF
