name: CI for Master Branch

on:
  push:
    branches:
      - master  # Trigger workflow on push events to the master branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests targeting the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Action to checkout the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Setup JDK 11
        distribution: 'adopt'  # Specify the distribution of JDK (e.g., adopt, adopt-openj9)

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository3
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache Maven dependencies

    - name: Build and Test
      run: mvn clean test  # Replace with your Maven command to build and run tests
      working-directory: Telelink_first/Telelink_first  # Specify the working directory where pom.xml is located

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports
        path: Telelink_first/Telelink_first/target/cucumber-reports/  # Path to save BDD test reports
