name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Navigate to the directory
      run: cd Telelink_first  # Replace with your actual directory if different
      working-directory: ${{ github.workspace }}/Telelink_first

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests from AccountPage.java
      run: mvn -Dtest=com.iinsight.pages.AccountPage test
