name: Java CI with Maven and Cucumber

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:

    runs-on: windows-latest  # Use the latest version of Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      path: C:\Users\Shashank\git\repository3  # Adjust path to match your local repository path

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ github.token }}

    - name: Build with Maven
      run: mvn clean verify
      working-directory: C:\Users\Shashank\git\repository3\Wosler_Automation  # Specify the correct directory containing pom.xml

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports
        path: C:\Users\Shashank\git\repository3\Wosler_Automation\target\cucumber-reports  # Adjust path based on your project structure

    - name: Publish test results
      if: always()  # Always publish test results even if build fails
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: C:\Users\Shashank\git\repository3\Wosler_Automation\target\surefire-reports  # Adjust path based on your project structure
